"""create core tables

Revision ID: 40632c6ed9a5
Revises: 
Create Date: 2026-07-26 23:44:21.764173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40632c6ed9a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misconceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_code'), 'misconceptions', ['code'], unique=True)
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('expected_language', sa.String(length=50), nullable=True),
    sa.Column('rule_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_code'), 'problems', ['code'], unique=True)
    op.create_table('student_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.Column('pseudonymous_id', sa.String(length=40), nullable=False),
    sa.Column('consent_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_aliases_pseudonymous_id'), 'student_aliases', ['pseudonymous_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_alias_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('written_reasoning', sa.Text(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('speech_transcript', sa.Text(), nullable=True),
    sa.Column('selected_language', sa.String(length=20), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_alias_id'], ['student_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_problem_id'), 'attempts', ['problem_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_alias_id'), 'attempts', ['student_alias_id'], unique=False)
    op.create_table('diagnostic_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('misconception_id', sa.UUID(), nullable=False),
    sa.Column('competing_misconception_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competing_misconception_id'], ['misconceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_questions_competing_misconception_id'), 'diagnostic_questions', ['competing_misconception_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_questions_misconception_id'), 'diagnostic_questions', ['misconception_id'], unique=False)
    op.create_table('hint_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('misconception_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('misconception_id', 'level', name='uq_hint_misconception_level')
    )
    op.create_index(op.f('ix_hint_templates_misconception_id'), 'hint_templates', ['misconception_id'], unique=False)
    op.create_table('problem_misconceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('misconception_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'misconception_id', name='uq_problem_misconception')
    )
    op.create_index(op.f('ix_problem_misconceptions_misconception_id'), 'problem_misconceptions', ['misconception_id'], unique=False)
    op.create_index(op.f('ix_problem_misconceptions_problem_id'), 'problem_misconceptions', ['problem_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('primary_misconception_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_misconception_id'], ['misconceptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_attempt_id'), 'diagnoses', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_primary_misconception_id'), 'diagnoses', ['primary_misconception_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_state'), 'diagnoses', ['state'], unique=False)
    op.create_table('diagnosis_alternatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('misconception_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_alternatives_diagnosis_id'), 'diagnosis_alternatives', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_alternatives_misconception_id'), 'diagnosis_alternatives', ['misconception_id'], unique=False)
    op.create_table('diagnosis_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_evidence_diagnosis_id'), 'diagnosis_evidence', ['diagnosis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_evidence_diagnosis_id'), table_name='diagnosis_evidence')
    op.drop_table('diagnosis_evidence')
    op.drop_index(op.f('ix_diagnosis_alternatives_misconception_id'), table_name='diagnosis_alternatives')
    op.drop_index(op.f('ix_diagnosis_alternatives_diagnosis_id'), table_name='diagnosis_alternatives')
    op.drop_table('diagnosis_alternatives')
    op.drop_index(op.f('ix_diagnoses_state'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_primary_misconception_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_attempt_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_problem_misconceptions_problem_id'), table_name='problem_misconceptions')
    op.drop_index(op.f('ix_problem_misconceptions_misconception_id'), table_name='problem_misconceptions')
    op.drop_table('problem_misconceptions')
    op.drop_index(op.f('ix_hint_templates_misconception_id'), table_name='hint_templates')
    op.drop_table('hint_templates')
    op.drop_index(op.f('ix_diagnostic_questions_misconception_id'), table_name='diagnostic_questions')
    op.drop_index(op.f('ix_diagnostic_questions_competing_misconception_id'), table_name='diagnostic_questions')
    op.drop_table('diagnostic_questions')
    op.drop_index(op.f('ix_attempts_student_alias_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_problem_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_student_aliases_pseudonymous_id'), table_name='student_aliases')
    op.drop_table('student_aliases')
    op.drop_index(op.f('ix_problems_code'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_misconceptions_code'), table_name='misconceptions')
    op.drop_table('misconceptions')
    # ### end Alembic commands ###
