"""add sprint 9 intervention and retry models

Revision ID: fd71c245bc0d
Revises: bf7a91b16011
Create Date: 2026-08-06 01:35:09.192481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd71c245bc0d'
down_revision: Union[str, Sequence[str], None] = 'bf7a91b16011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_alias_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_question_id', sa.UUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('evaluated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(trim(response_text)) >= 1', name='ck_diagnostic_responses_text_not_blank'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_question_id'], ['diagnostic_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_alias_id'], ['student_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'diagnostic_question_id', name='uq_diagnostic_responses_diagnosis_question')
    )
    op.create_index('ix_diagnostic_responses_attempt_created_at', 'diagnostic_responses', ['attempt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_attempt_id'), 'diagnostic_responses', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_created_at'), 'diagnostic_responses', ['created_at'], unique=False)
    op.create_index('ix_diagnostic_responses_diagnosis_created_at', 'diagnostic_responses', ['diagnosis_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_diagnosis_id'), 'diagnostic_responses', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_diagnostic_question_id'), 'diagnostic_responses', ['diagnostic_question_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_evaluated'), 'diagnostic_responses', ['evaluated'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_evaluated_at'), 'diagnostic_responses', ['evaluated_at'], unique=False)
    op.create_index('ix_diagnostic_responses_evaluated_created_at', 'diagnostic_responses', ['evaluated', 'created_at'], unique=False)
    op.create_index('ix_diagnostic_responses_question_created_at', 'diagnostic_responses', ['diagnostic_question_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_student_alias_id'), 'diagnostic_responses', ['student_alias_id'], unique=False)
    op.create_index('ix_diagnostic_responses_student_created_at', 'diagnostic_responses', ['student_alias_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_responses_updated_at'), 'diagnostic_responses', ['updated_at'], unique=False)
    op.create_table('hint_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_alias_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('hint_template_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 3', name='ck_hint_events_level_range'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hint_template_id'], ['hint_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_alias_id'], ['student_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'level', name='uq_hint_events_diagnosis_level')
    )
    op.create_index('ix_hint_events_attempt_created_at', 'hint_events', ['attempt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_hint_events_attempt_id'), 'hint_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_hint_events_created_at'), 'hint_events', ['created_at'], unique=False)
    op.create_index('ix_hint_events_diagnosis_created_at', 'hint_events', ['diagnosis_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_hint_events_diagnosis_id'), 'hint_events', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_hint_events_hint_template_id'), 'hint_events', ['hint_template_id'], unique=False)
    op.create_index(op.f('ix_hint_events_student_alias_id'), 'hint_events', ['student_alias_id'], unique=False)
    op.create_index('ix_hint_events_student_created_at', 'hint_events', ['student_alias_id', 'created_at'], unique=False)
    op.create_index('ix_hint_events_template_created_at', 'hint_events', ['hint_template_id', 'created_at'], unique=False)
    op.create_table('misconception_evolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_alias_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('previous_attempt_id', sa.UUID(), nullable=True),
    sa.Column('previous_diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('previous_misconception_id', sa.UUID(), nullable=True),
    sa.Column('current_misconception_id', sa.UUID(), nullable=True),
    sa.Column('previous_diagnosis_state', sa.String(length=30), nullable=True),
    sa.Column('current_diagnosis_state', sa.String(length=30), nullable=False),
    sa.Column('evolution_state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("current_diagnosis_state IN ('confident', 'possible', 'insufficient', 'no_misconception')", name='ck_misconception_evolutions_valid_current_diagnosis_state'),
    sa.CheckConstraint("evolution_state IN ('newly_detected', 'repeated', 'improving', 'corrected', 'replaced', 'uncertain')", name='ck_misconception_evolutions_valid_state'),
    sa.CheckConstraint("previous_diagnosis_state IS NULL OR previous_diagnosis_state IN ('confident', 'possible', 'insufficient', 'no_misconception')", name='ck_misconception_evolutions_valid_previous_diagnosis_state'),
    sa.CheckConstraint('(previous_attempt_id IS NULL AND previous_diagnosis_id IS NULL) OR (previous_attempt_id IS NOT NULL AND previous_diagnosis_id IS NOT NULL)', name='ck_misconception_evolutions_previous_reference_consistency'),
    sa.CheckConstraint('previous_attempt_id IS NULL OR previous_attempt_id <> attempt_id', name='ck_misconception_evolutions_attempt_not_self'),
    sa.CheckConstraint('previous_diagnosis_id IS NULL OR previous_diagnosis_id <> diagnosis_id', name='ck_misconception_evolutions_diagnosis_not_self'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_misconception_id'], ['misconceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_misconception_id'], ['misconceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_alias_id'], ['student_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', name='uq_misconception_evolutions_diagnosis')
    )
    op.create_index('ix_misconception_evolutions_attempt_created_at', 'misconception_evolutions', ['attempt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_attempt_id'), 'misconception_evolutions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_created_at'), 'misconception_evolutions', ['created_at'], unique=False)
    op.create_index('ix_misconception_evolutions_current_misconception', 'misconception_evolutions', ['current_misconception_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_current_misconception_id'), 'misconception_evolutions', ['current_misconception_id'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_diagnosis_id'), 'misconception_evolutions', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_evolution_state'), 'misconception_evolutions', ['evolution_state'], unique=False)
    op.create_index('ix_misconception_evolutions_previous_attempt', 'misconception_evolutions', ['previous_attempt_id'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_previous_attempt_id'), 'misconception_evolutions', ['previous_attempt_id'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_previous_diagnosis_id'), 'misconception_evolutions', ['previous_diagnosis_id'], unique=False)
    op.create_index('ix_misconception_evolutions_previous_misconception', 'misconception_evolutions', ['previous_misconception_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_previous_misconception_id'), 'misconception_evolutions', ['previous_misconception_id'], unique=False)
    op.create_index('ix_misconception_evolutions_problem_created_at', 'misconception_evolutions', ['problem_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_problem_id'), 'misconception_evolutions', ['problem_id'], unique=False)
    op.create_index('ix_misconception_evolutions_state_created_at', 'misconception_evolutions', ['evolution_state', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_student_alias_id'), 'misconception_evolutions', ['student_alias_id'], unique=False)
    op.create_index('ix_misconception_evolutions_student_created_at', 'misconception_evolutions', ['student_alias_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_misconception_evolutions_updated_at'), 'misconception_evolutions', ['updated_at'], unique=False)
    op.add_column('attempts', sa.Column('parent_attempt_id', sa.UUID(), nullable=True))
    op.add_column('attempts', sa.Column('retry_number', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_attempts_parent_attempt_id'), 'attempts', ['parent_attempt_id'], unique=False)
    op.create_index('ix_attempts_parent_created_at', 'attempts', ['parent_attempt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_attempts_retry_number'), 'attempts', ['retry_number'], unique=False)
    op.create_index('ix_attempts_student_problem_retry', 'attempts', ['student_alias_id', 'problem_id', 'retry_number'], unique=False)
    op.create_foreign_key('fk_attempts_parent_attempt_id', 'attempts', 'attempts', ['parent_attempt_id'], ['id'], ondelete='SET NULL')
    op.add_column(
        'diagnoses',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
    )
    op.alter_column(
        'diagnoses',
        'updated_at',
        existing_type=sa.DateTime(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column('diagnoses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='0',
               existing_nullable=False)
    op.alter_column('diagnoses', 'model_version',
               existing_type=sa.VARCHAR(length=80),
               server_default='rule-v1.4',
               existing_nullable=False)
    op.create_index('ix_diagnoses_attempt_created_at', 'diagnoses', ['attempt_id', 'created_at'], unique=False)
    op.create_index('ix_diagnoses_attempt_state', 'diagnoses', ['attempt_id', 'state'], unique=False)
    op.create_index('ix_diagnoses_state_next_action', 'diagnoses', ['state', 'next_action'], unique=False)
    op.create_index(op.f('ix_diagnoses_updated_at'), 'diagnoses', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_diagnoses_attempt_model_version', 'diagnoses', ['attempt_id', 'model_version'])
    op.add_column(
        'diagnostic_questions',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
    )
    op.alter_column(
        'diagnostic_questions',
        'updated_at',
        existing_type=sa.DateTime(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column('diagnostic_questions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.create_index(op.f('ix_diagnostic_questions_active'), 'diagnostic_questions', ['active'], unique=False)
    op.create_index(op.f('ix_diagnostic_questions_approved_by'), 'diagnostic_questions', ['approved_by'], unique=False)
    op.create_index('ix_diagnostic_questions_competing_active', 'diagnostic_questions', ['competing_misconception_id', 'active'], unique=False)
    op.create_index('ix_diagnostic_questions_created_at', 'diagnostic_questions', ['created_at'], unique=False)
    op.create_index('ix_diagnostic_questions_misconception_active', 'diagnostic_questions', ['misconception_id', 'active'], unique=False)
    op.add_column(
        'hint_templates',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
    )
    op.alter_column(
        'hint_templates',
        'updated_at',
        existing_type=sa.DateTime(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column('hint_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.create_index(op.f('ix_hint_templates_active'), 'hint_templates', ['active'], unique=False)
    op.create_index(op.f('ix_hint_templates_approved_by'), 'hint_templates', ['approved_by'], unique=False)
    op.create_index('ix_hint_templates_created_at', 'hint_templates', ['created_at'], unique=False)
    op.create_index('ix_hint_templates_level', 'hint_templates', ['level'], unique=False)
    op.create_index('ix_hint_templates_misconception_active', 'hint_templates', ['misconception_id', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hint_templates_misconception_active', table_name='hint_templates')
    op.drop_index('ix_hint_templates_level', table_name='hint_templates')
    op.drop_index('ix_hint_templates_created_at', table_name='hint_templates')
    op.drop_index(op.f('ix_hint_templates_approved_by'), table_name='hint_templates')
    op.drop_index(op.f('ix_hint_templates_active'), table_name='hint_templates')
    op.alter_column('hint_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('hint_templates', 'updated_at')
    op.drop_index('ix_diagnostic_questions_misconception_active', table_name='diagnostic_questions')
    op.drop_index('ix_diagnostic_questions_created_at', table_name='diagnostic_questions')
    op.drop_index('ix_diagnostic_questions_competing_active', table_name='diagnostic_questions')
    op.drop_index(op.f('ix_diagnostic_questions_approved_by'), table_name='diagnostic_questions')
    op.drop_index(op.f('ix_diagnostic_questions_active'), table_name='diagnostic_questions')
    op.alter_column('diagnostic_questions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('diagnostic_questions', 'updated_at')
    op.drop_constraint('uq_diagnoses_attempt_model_version', 'diagnoses', type_='unique')
    op.drop_index(op.f('ix_diagnoses_updated_at'), table_name='diagnoses')
    op.drop_index('ix_diagnoses_state_next_action', table_name='diagnoses')
    op.drop_index('ix_diagnoses_attempt_state', table_name='diagnoses')
    op.drop_index('ix_diagnoses_attempt_created_at', table_name='diagnoses')
    op.alter_column('diagnoses', 'model_version',
               existing_type=sa.VARCHAR(length=80),
               server_default=None,
               existing_nullable=False)
    op.alter_column('diagnoses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_column('diagnoses', 'updated_at')
    op.drop_constraint('fk_attempts_parent_attempt_id', 'attempts', type_='foreignkey')
    op.drop_index('ix_attempts_student_problem_retry', table_name='attempts')
    op.drop_index(op.f('ix_attempts_retry_number'), table_name='attempts')
    op.drop_index('ix_attempts_parent_created_at', table_name='attempts')
    op.drop_index(op.f('ix_attempts_parent_attempt_id'), table_name='attempts')
    op.drop_column('attempts', 'retry_number')
    op.drop_column('attempts', 'parent_attempt_id')
    op.drop_index(op.f('ix_misconception_evolutions_updated_at'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_student_created_at', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_student_alias_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_state_created_at', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_problem_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_problem_created_at', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_previous_misconception_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_previous_misconception', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_previous_diagnosis_id'), table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_previous_attempt_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_previous_attempt', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_evolution_state'), table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_diagnosis_id'), table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_current_misconception_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_current_misconception', table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_created_at'), table_name='misconception_evolutions')
    op.drop_index(op.f('ix_misconception_evolutions_attempt_id'), table_name='misconception_evolutions')
    op.drop_index('ix_misconception_evolutions_attempt_created_at', table_name='misconception_evolutions')
    op.drop_table('misconception_evolutions')
    op.drop_index('ix_hint_events_template_created_at', table_name='hint_events')
    op.drop_index('ix_hint_events_student_created_at', table_name='hint_events')
    op.drop_index(op.f('ix_hint_events_student_alias_id'), table_name='hint_events')
    op.drop_index(op.f('ix_hint_events_hint_template_id'), table_name='hint_events')
    op.drop_index(op.f('ix_hint_events_diagnosis_id'), table_name='hint_events')
    op.drop_index('ix_hint_events_diagnosis_created_at', table_name='hint_events')
    op.drop_index(op.f('ix_hint_events_created_at'), table_name='hint_events')
    op.drop_index(op.f('ix_hint_events_attempt_id'), table_name='hint_events')
    op.drop_index('ix_hint_events_attempt_created_at', table_name='hint_events')
    op.drop_table('hint_events')
    op.drop_index(op.f('ix_diagnostic_responses_updated_at'), table_name='diagnostic_responses')
    op.drop_index('ix_diagnostic_responses_student_created_at', table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_student_alias_id'), table_name='diagnostic_responses')
    op.drop_index('ix_diagnostic_responses_question_created_at', table_name='diagnostic_responses')
    op.drop_index('ix_diagnostic_responses_evaluated_created_at', table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_evaluated_at'), table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_evaluated'), table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_diagnostic_question_id'), table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_diagnosis_id'), table_name='diagnostic_responses')
    op.drop_index('ix_diagnostic_responses_diagnosis_created_at', table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_created_at'), table_name='diagnostic_responses')
    op.drop_index(op.f('ix_diagnostic_responses_attempt_id'), table_name='diagnostic_responses')
    op.drop_index('ix_diagnostic_responses_attempt_created_at', table_name='diagnostic_responses')
    op.drop_table('diagnostic_responses')
    # ### end Alembic commands ###